FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY logo.png /usr/share/nginx/html/logo.png
COPY icon.jpg /usr/share/nginx/html/icon.jpg
COPY acceso.html /usr/share/nginx/html/acceso.html
COPY Logo_proyecto_recortado.png /usr/share/nginx/html/Logo_proyecto_recortado.png
COPY dashboard.html /usr/share/nginx/html/dashboard.html
COPY contratar.html /usr/share/nginx/html/contratar.html
COPY contratar.html /usr/share/nginx/html/contratar.html

EXPOSE 80

